#!/bin/sh

set -x
set -e

if [ ! "$CI" = "true" ]; then
   true "ERROR: You probably do not want to run this outside of a CI \
environment, because it uses virsh to undefine virtual machines."
   exit 1
fi

mydir="$( cd "$( dirname "$0" )" && pwd )"
cd "$mydir"
cd ..
cd ..
cd ..

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

dpkg-query --show --showformat='${Package} ${Version} \n' libvirt-bin qemu-kvm virt-manager || true

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

sudo chmod o+rwx /var/run/libvirt/libvirt-sock

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix_network.xml
virsh -c qemu:///system net-define ./usr/share/whonix-libvirt/xml/Whonix_network.xml
virsh -c qemu:///system net-autostart Whonix
virsh -c qemu:///system net-start Whonix || true

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

## Debugging.

virsh -c qemu:///system net-dumpxml default
virsh -c qemu:///system net-dumpxml default --inactive

virsh -c qemu:///system net-dumpxml Whonix
virsh -c qemu:///system net-dumpxml Whonix --inactive

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

for target in kvm; do
   virsh domxml-to-native qemu-argv ./usr/share/whonix-libvirt/xml/Whonix-Gateway_${target}.xml || true
   true "-----"
   virsh domxml-to-native qemu-argv ./usr/share/whonix-libvirt/xml/Whonix-Workstation_${target}.xml || true
   true "-----"
   virsh domxml-to-native qemu-argv ./usr/share/whonix-libvirt/xml/Whonix-Custom-Workstation_${target}.xml || true
   true "-----"
done

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

for target in kvm; do
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Gateway_${target}.xml || true
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Workstation_${target}.xml || true
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Custom-Workstation_${target}.xml || true
done

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

for target in kvm; do
   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Gateway_${target}.xml
   virsh -c qemu:///system undefine Whonix-Gateway

   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Workstation_${target}.xml
   virsh -c qemu:///system undefine Whonix-Workstation

   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Custom-Workstation_${target}.xml
   virsh -c qemu:///system undefine Whonix-Custom-Workstation
done

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

true "$0: All tests passed."
