#!/bin/sh

set -x
set -e

if [ ! "$CI" = "true" ]; then
   true "ERROR: You probably do not want to run this outside of a CI \
environment, because it uses virsh to undefine virtual machines."
   exit 1
fi

mydir="$( cd "$( dirname "$0" )" && pwd )"
cd "$mydir"
cd ..
cd ..
cd ..

sudo chmod o+rwx /var/run/libvirt/libvirt-sock

virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix_network.xml
virsh -c qemu:///system net-define ./usr/share/whonix-libvirt/xml/Whonix_network.xml
virsh -c qemu:///system net-autostart Whonix
virsh -c qemu:///system net-start Whonix || true

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

for target in kvm qemu; do
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Gateway_${target}.xml || true
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Workstation_${target}.xml || true
   virt-xml-validate ./usr/share/whonix-libvirt/xml/Whonix-Custom-Workstation_${target}.xml || true
done

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

for target in kvm qemu; do
   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Gateway_${target}.xml || true
   virsh -c qemu:///system undefine Whonix-Gateway || true

   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Workstation_${target}.xml || true
   virsh -c qemu:///system undefine Whonix-Workstation || true

   virsh -c qemu:///system define ./usr/share/whonix-libvirt/xml/Whonix-Custom-Workstation_${target}.xml || true
   virsh -c qemu:///system undefine Whonix-Custom-Workstation || true
done

true "------------------------------------------------------------"
true "------------------------------------------------------------"
true "------------------------------------------------------------"

true "$0: All tests passed."
