#!/bin/bash

## Copyright (C) 2020 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://forums.whonix.org/t/whonix-host-operating-system/3931/236

title="WARNING - Whonix-Host DEVELOPERS-ONLY Preview Version"

text="\
<p>
DO NOT USE THIS YET AS A USER!
<br />
Whonix-Host is unreleased. Not even available for testers. This version is a preview for developers only.<br />
<br />
Missing features the the initial release include

<ul>
  <li><a href=https://phabricator.whonix.org/T978>Whonix-Host EFI booting support</a></li>
  <li><a href=https://phabricator.whonix.org/T942>Whonix Host Firewall for Whonix Host</a></li>
  <li><a href=https://phabricator.whonix.org/T981>Whonix-Host Tor configuration and anon-connection-wizard (ACW)</a></p></li>
</ul>

See <a href=https://phabricator.whonix.org/maniphest/query/_Obk7yld9FTN/#R>full task list for first release of Whonix-Host</a>.<br />
<br />
Help welcome!
</p>
"

mkdir -p ~/.config/whonix/host-boot-popup
/usr/libexec/msgcollector/one-time-popup ~/.config/whonix/host-boot-popup/dismissed_version_1 "$title" "$text"
