#!/bin/bash

## Copyright (C) 2020 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://forums.whonix.org/t/whonix-host-operating-system/3931/236

title="WARNING - Whonix-Host DEVELOPERS-ONLY Preview Version"

text="\
<p>
DO NOT USE THIS YET AS A USER!
<br />
Whonix-Host is unreleased. Not even available for testers. This version is a preview for developers only.<br />
<br />
Missing features the the initial release include

<ul>
  <li><a href=https://forums.whonix.org/t/whonix-host-firewall-for-whonix-host/18498>Whonix Host Firewall for Whonix Host</a></li>
  <li><a href=https://forums.whonix.org/t/whonix-host-tor-configuration-and-anon-connection-wizard-acw-ipv6-disable-ipv4-forward-disable/18452>Whonix-Host Tor configuration and anon-connection-wizard (ACW)</a></p></li>
</ul>

See <a href=https://forums.whonix.org/search?q=tags%3Astatus_open_issue_todo%2Bcomponent_whonix-host>full task list for first release of Whonix-Host</a>.<br />
<br />
Help welcome!
</p>
"

mkdir -p ~/.config/whonix/host-boot-popup
/usr/libexec/msgcollector/one-time-popup ~/.config/whonix/host-boot-popup/dismissed_version_1 "$title" "$text"
