#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

## Doing the following in a temporary directory to avoid modified files should
## this be interrupted in the middle.
temp_dir="$(mktemp --directory)"
cp -r /usr/share/whonix-libvirt/xml "$temp_dir"

## workaround to replace the 'kvm' domain type with 'qemu' otherwise libvirtd service will fail to start in chroot
sed -i "1 s/^.*$/<domain type='qemu'>/" "$temp_dir/xml/Whonix-Gateway.xml"
sed -i "1 s/^.*$/<domain type='qemu'>/" "$temp_dir/xml/Whonix-Workstation.xml"

if systemctl --no-pager status libvirtd >/dev/null ; then
   true "libvirtd is running."
else
   if [ "$stop_libvirtd" = "" ]; then
      stop_libvirtd="true"
      true "libvirtd is not running, starting it now and stopping it at the end."
   fi

   ## starting the libvirtd service so we can define Whonix networks and domain
   ## of course a clean script would use variables instead of version numbers
   systemctl --no-pager start libvirtd
fi

virsh -c qemu:///system net-autostart "default"
virsh -c qemu:///system net-start "default"
virsh -c qemu:///system net-define "/usr/share/whonix-libvirt/xml/Whonix-External.xml"
virsh -c qemu:///system net-define "/usr/share/whonix-libvirt/xml/Whonix-Internal.xml"
virsh -c qemu:///system net-autostart "Whonix-External"
virsh -c qemu:///system net-start "Whonix-External"
virsh -c qemu:///system net-autostart "Whonix-Internal"
virsh -c qemu:///system net-start "Whonix-Internal"
virsh -c qemu:///system define "$temp_dir/xml/Whonix-Gateway.xml"
virsh -c qemu:///system define "$temp_dir/xml/Whonix-Workstation.xml"

if [ "$stop_libvirtd" = "true" ]; then
   true "libvirtd was not running before running this script, so stopping it now."
   systemctl --no-pager stop libvirtd
fi
